// <auto-generated />
using CardsCrib.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace CardsCrib.DAL.Migrations
{
    [DbContext(typeof(CardsCribContext))]
    [Migration("20180503215310_CardsCrib.DAL.CardsCribContext")]
    partial class CardsCribDALCardsCribContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CardsCrib.Models.Card", b =>
                {
                    b.Property<long>("CardId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("CardId");

                    b.ToTable("Card");
                });
#pragma warning restore 612, 618
        }
    }
}
